### ISSUE TITLE
32-bit compatibility

### ISSUE THREAD

**Issue by Giotino** [m1dugh/native-sound-mixer#14]
Hi, I wasn't able to get this module (from npm and from the `master` branch) working on my machine (Node v16.2.0 **x86** on Windows).
I noted that

```js
const { arch } = require('os');
console.log(arch());
```

is printing 'ia32' on my machine (instead of the 'x32' expected by this module).

An easy fix would be to replace this line

https://github.com/m1dugh/native-sound-mixer/blob/fede9f91872254c96747315d5d0518253c81fe7a/src/sound-mixer.ts#L8

with

```js
if (arch() === "x32" || arch() === "x64" || arch() === "ia32") {
```

With this patch the module works fine.

**Comment by m1dugh** [comment]
This is fixed as of version 3.2.3, thanks for the issue and the resolution.
