### ISSUE TITLE
Per app audio panning function

### ISSUE THREAD

**Issue by cepsong** [m1dugh/native-sound-mixer#16]
Is it possible to add in the control of per app audio panning (to the left or right channel) by scripts? This is highly appreciated!

**Comment by cepsong** [comment]
An example could be:
Application A:
L - 25%
R - 0%

Application B:

L - 0%
R - 100%

You could editing a video (B) , but still not detached from listening to a news or music stream (A). Possible to do this?

**Comment by m1dugh** [comment]
This could be possible it might take a little bit of time to develop i'll be working on it soon.

**Comment by cepsong** [comment]
Can you be a bit more specific? Would the link I shared be helpful in getting some ideas to pan the channels per app?
