### ISSUE TITLE
Read audio device current levels (meter)

### ISSUE THREAD

**Issue by fu-raz** [m1dugh/native-sound-mixer#21]
Would it be possible to get the current level of the audio being played on a specific device? 

I know Windows knows the current level, but I don't know if you can read these levels through C++
![image](https://user-images.githubusercontent.com/5355154/206454922-9995e399-cf57-40c1-b9ff-6d83197b7f9f.png)

**Comment by m1dugh** [comment]
It is all explained in the documentation in the README file

**Comment by fu-raz** [comment]
I meant like a UV meter not so much the audio level

**Comment by m1dugh** [comment]
It is a node js API, therefore there is no like display or whatever, you can read the levels but you cannot display it with the API.

**Comment by m1dugh** [comment]
You are absolutely right. Right now there is no way to know this. However, the functionalities you are looking for are available in the `Windows core audio API`. You can make a PR to provide this enhancement if you want.

**Comment by fu-raz** [comment]
Thanks for pointing me in the right direction! I'll see if I'm able to get this working
