### ISSUE TITLE
Feat: `pkg-prebuilds`

### ISSUE THREAD

**Issue by hrueger** [m1dugh/native-sound-mixer#23]
Hi @m1dugh,
are you interested in me making a PR to add @Julusian's excellent [`pkg-prebuilds`](https://github.com/Julusian/pkg-prebuilds) tooling?

This would add a GitHub Action which would build the prebuild binaries on Windows and Linux for amd64 (maybe also amd64).
Then, you could ship those directly in the pakage published on npm. This has the benefit of not requiring users to have a working node-gyp build environment as well as easy cross-compilation (as in fact no compilation should be needed when installing the lib).

Let me know what you think.

**Comment by m1dugh** [comment]
If you can make it work properly, it could be nice indeed. I'll look further into github actions as soon as I can.

**Comment by hrueger** [comment]
Sure, I'll make a PR in the next couple days 👍

**Comment by m1dugh** [comment]
I've started adding CI with github actions in branch `27-add-basic-cicd-for-push-event` using `cmake-js` to replace `node-gyp`

**Comment by hrueger** [comment]
Cool. How would you like me to proceed here? Should I add the `pkg-prebuilds` to a new PR based on that branch or rather wait until you merge #28? The latter is probably less complicated.

**Comment by m1dugh** [comment]
I will merge the ci PR soon so it might be easier to wait.

**Comment by m1dugh** [comment]
I merged the CI to develop, alongwith the `cmake-js` build replacing `node-gyp`

**Comment by hrueger** [comment]
Thanks, I'll try to make a PR tomorrow 👍
