### ISSUE TITLE
Cannot install package from npm

### ISSUE THREAD

**Issue by beeloon** [m1dugh/native-sound-mixer#44]
@m1dugh Hello sir!
Currently, I'm working on electron project where we need to control app audio session for some features, but when i tried to install your package via npm I receive an error like this:
![Screenshot 2023-12-04 145612](https://github.com/m1dugh/native-sound-mixer/assets/35525965/27d97b75-d586-49a4-95e1-a8aa342d6679)

From the message I can see that error point out to CMake, is it necessary to have the software to be installed on developer machine to proceed using the package, or I can fix it in other way?

Thank you :bow:

**Comment by m1dugh** [comment]
Hello,
It should not be necessary to have cmake, npm package should come with pre compiled binaries.
Sorry for late response time, I'll check that as soon as I can

**Comment by m1dugh** [comment]
Can you check which version you installed please ?

**Comment by m1dugh** [comment]
The issue os with the install target in the package.json file.
I'll remove it and push to npm again.

**Comment by beeloon** [comment]
@m1dugh thank you, here's the info you required:
OS - Windows 11
Node - v18.17.1
NPM - 9.6.7

Installing last version of native-sound-mixer package from NPM
As I can see, it's 3.4.3-win

**Comment by m1dugh** [comment]
As stated earlier, I might have found the issue, I'll try and deploy a fix by tomorrow that will hopefully solve your problem.

**Comment by m1dugh** [comment]
Hello again,
It should be fixed, please confirm me if it is :heart: 

Sorry again for delay.

**Comment by beeloon** [comment]
@m1dugh Sir, it's actually fixed, thank you very much 🙇 

Also, it might be off top, but when I'm trying to use your library, I cannot see any available devices when I'm running test script (screenshots)
And getDefaultDevice function actually exists on autocomplete in TS files but when i run the script it says that the function does not exist, can you please confirm is that an issue on my end (wrong code, calling library dependency or machine issues, etc.)
I'd be very grateful :bow:
![Screenshot 2023-12-28 123949](https://github.com/m1dugh/native-sound-mixer/assets/35525965/0a12de34-b346-4467-880a-abdfa8592cdc)
![Screenshot 2023-12-28 124055](https://github.com/m1dugh/native-sound-mixer/assets/35525965/3133d882-9555-4477-a55d-1688a53b5f37)

**Comment by m1dugh** [comment]
I don't know electron very much, but are you sure you are running your code server-side ?
I'll check as soon as I can on my side since it might be an issue on my side,
Thanks for feedback.

**Comment by beeloon** [comment]
@m1dugh actually I tried to run it in electron and in clean testing project only with node(only add index.js file, run npm init, and downloaded library), and the result the same

**Comment by m1dugh** [comment]
I'll try it out myself and keep you up to date.
I think it should be resolved within a week.

**Comment by m1dugh** [comment]
Sorry it took so long, I tried on my side, and it works well.
Here is a picture of what I tried
![image](https://github.com/m1dugh/native-sound-mixer/assets/42266017/f069a37a-bef3-47b4-bbc7-c91edc73731f)

If your problem persists, please include more details.
